stages:
  - build
  - test
  - docker
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/engripaye/notes-app-gitlab-cicd


  # Build Stage
build_image:
  stage: build
  image: maven:3.9.4-eclipse-temurin-21
  script:
    - mvn clean package -DskipTests


  # Test Stage
test-job:
  stage: test
  image: maven:3.9.4-eclipse-temurin-21
  script:
    - mvn test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml


  # Docker Build & Push
docker-build:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
  only:
    - main

  # Deploy to Staging
deploy-staging:
  stage: deploy
  script:
    - echo "Deploying $DOCKER_IMAGE:$CI_COMMIT_SHA to staging..."

  # kubectl apply -f k8s or docker compose up
  environment:
    name: staging
  only:
    - main
